title: Reagan's Blog
subtitle: null
description: A Blog About Software and Various Other Things I Find Interesting
author: Josh Reagan
language: en
timezone: null
url: 'https://blog.joshdreagan.com/'
root: /
permalink: ':year/:month/:day/:title/'
permalink_defaults: null
pretty_urls:
  trailing_index: false
  trailing_html: false
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: ':lang'
skip_render: null
new_post_name: ':title.md'
default_layout: post
titlecase: true
external_link:
  enable: true
  field: site
  exclude: ''
filename_case: 1
render_drafts: false
post_asset_folder: true
relative_link: false
future: false
highlight:
  enable: true
  line_number: true
  auto_detect: false
  tab_replace: ''
  wrap: true
  hljs: false
prismjs:
  enable: false
  preprocess: true
  line_number: true
  tab_replace: ''
index_generator:
  path: ''
  per_page: 5
  order_by: '-date'
default_category: uncategorized
category_map: null
tag_map: null
meta_generator: true
date_format: YYYY-MM-DD
time_format: 'HH:mm:ss'
updated_option: mtime
per_page: 0
pagination_dir: page
include: null
exclude:
  - "**/*.xcf"
ignore: null
theme: icarus
feed:
  type: atom
  path: atom.xml
  limit: 20
deploy:
  - type: git
    repo: 'git@github.com:joshdreagan/joshdreagan.github.io.git'
    branch: master
