version: 5.1.0
variant: default
logo: /img/logo.png
head:
    favicon: /img/favicon.png
    manifest:
        name: 
        short_name: 
        start_url: 
        theme_color: 
        background_color: 
        display: standalone
        icons:
            -
                src: ''
                sizes: ''
                type: 
    open_graph:
        title: 
        type: blog
        url: 
        image: 
        site_name: 
        author: 
        description: 
        twitter_card: 
        twitter_id: 
        twitter_site: 
        google_plus: 
        fb_admins: 
        fb_app_id: 
    structured_data:
        title: 
        description: 
        url: 
        author: 
        image: 
    meta:
        - ''
    rss: /atom.xml
navbar:
    menu:
        Home: /
        Archives: /archives
        Tags: /tags
    links: 
footer:
    links:
        Creative Commons:
            icon: fab fa-creative-commons
            url: https://creativecommons.org/
        Attribution 4.0 International:
            icon: fab fa-creative-commons-by
            url: https://creativecommons.org/licenses/by/4.0/
        Download on GitHub:
            icon: fab fa-github
            url: https://github.com/ppoffice/hexo-theme-icarus
article:
    highlight:
        theme: atom-one-light
        clipboard: true
        fold: unfolded
    readtime: false
    licenses:
        Creative Commons:
            icon: fab fa-creative-commons
            url: https://creativecommons.org/
        Attribution:
            icon: fab fa-creative-commons-by
            url: https://creativecommons.org/licenses/by/4.0/
        Noncommercial:
            icon: fab fa-creative-commons-nc
            url: https://creativecommons.org/licenses/by-nc/4.0/
search:
    type: insight
sidebar:
    left:
        sticky: false
    right:
        sticky: false
widgets:
    -
        position: left
        type: profile
        author: Josh Reagan
        author_title: Software Engineer
        location: Colorado, USA
        avatar_rounded: false
        gravatar: josh.d.reagan@gmail.com
        follow_link: https://github.com/joshdreagan
        social_links:
            Github:
                icon: fab fa-github
                url: https://github.com/joshdreagan
            Twitter:
                icon: fab fa-twitter
                url: https://twitter.com/joshdreagan
            LinkedIn:
                icon: fab fa-linkedin
                url: https://www.linkedin.com/in/joshdreagan
            RSS:
                icon: fas fa-rss
                url: /atom.xml
    -
        position: left
        type: toc
        index: true
        collapsed: true
        depth: 3
    -
        position: right
        type: recent_posts
    -
        position: right
        type: archives
    -
        position: right
        type: tags
plugins:
    animejs: true
    back_to_top: true
    busuanzi: false
    gallery: true
    google_analytics:
        tracking_id: UA-81075900-1
    katex: false
    mathjax: false
    outdated_browser: false
    progressbar: true
providers:
    cdn: jsdelivr
    fontcdn: google
    iconcdn: fontawesome
